src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>N_10__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-10</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_111__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N+11</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_11__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-11</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-5</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_6__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-6</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_7__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-7</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_8__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-8</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_9__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N-9</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_mes_en_curso__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N mes en curso</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>N_mes_vencimiento_posterior__c</fullName>
        <defaultValue>false</defaultValue>
        <label>N mes vencimiento posterior</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RUT__c</fullName>
        <externalId>true</externalId>
        <label>RUT</label>
        <length>11</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Situaci_n_Laboral__c</fullName>
        <label>Situación Laboral</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Amicar/src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Concesionario__c</fullName>
        <label>Concesionario</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Importadores__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Concesionario</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EF_Original__c</fullName>
        <label>EF Original</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Egresos__c</fullName>
        <label>Egresos</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ejecutivo_Call__c</fullName>
        <label>Ejecutivo Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Jocelyn Umaña</fullName>
                </value>
                <value>
                    <fullName>Karem Peñaloza</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estado_Cierre__c</fullName>
        <label>Estado Cierre</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>VIGENTE</fullName>
                </value>
                <value>
                    <fullName>RENOVADO</fullName>
                </value>
                <value>
                    <fullName>PREPAGADO</fullName>
                </value>
                <value>
                    <fullName>RECHAZADO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estado_Solicitud__c</fullName>
        <label>Estado Solicitud</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>APROBADA</fullName>
                </value>
                <value>
                    <fullName>RECHAZADA</fullName>
                </value>
                <value>
                    <fullName>CONDICIONADA</fullName>
                </value>
                <value>
                    <fullName>NO ACCESADA</fullName>
                </value>
                <value>
                    <fullName>PENDIENTE O EN PROCESO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estado_cr_dito__c</fullName>
        <label>Estado crédito</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fecha_Hora_Ultimo_Evento__c</fullName>
        <label>Fecha/Hora Ultimo Evento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fecha_de_Vencimiento_Cuoton__c</fullName>
        <label>Fecha de Vencimiento Cuoton</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_ingreso_empleo__c</fullName>
        <label>Fecha ingreso empleo</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fecha_ltima_Cuota__c</fullName>
        <label>Fecha Última Cuota</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Id_Credito__c</fullName>
        <externalId>true</externalId>
        <label>IdCredito</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Importadores__c</fullName>
        <label>Importadores</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Importadores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Local__c</fullName>
        <label>Local</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Concesionario__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Locales</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marca_Veh_culo__c</fullName>
        <label>Marca Vehículo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Marcas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>N_10__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-2)</formula>
        <label>N-10</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_1__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-11)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>N-1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_2__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-10)</formula>
        <label>N-2</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_3__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-9)</formula>
        <label>N-3</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_4__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-8)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>N-4</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_5__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-7)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>N-5</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_6__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-6)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>N-6</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_7__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-5)</formula>
        <label>N-7</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_8__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-4)</formula>
        <label>N-8</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>N_9__c</fullName>
        <formula>ADDMONTHS(Primer_dia_vencimiento__c,-3)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>N-9</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Nombre_EF__c</fullName>
        <label>Nombre EF</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Entidades_Financieras</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preevaluacion_EF__c</fullName>
        <label>Preevaluación EF</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Preaprobado</fullName>
                </value>
                <value>
                    <fullName>Prepagado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Refinanciamiento</fullName>
                </value>
                <value>
                    <fullName>Prepago anticipado (1-6)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Respuesta_EF__c</fullName>
        <label>Respuesta EF</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>Preaprobado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Prepagado</fullName>
                </value>
                <value>
                    <fullName>Sujeto a evaluación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sueldo_Liquido__c</fullName>
        <label>Sueldo Liquido</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Contrato__c</fullName>
        <label>Tipo de Contrato</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Indefinido</fullName>
                </value>
                <value>
                    <fullName>Plazo Fijo</fullName>
                </value>
                <value>
                    <fullName>Contrata</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo_de_Credito__c</fullName>
        <label>Tipo de Credito</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_a_Financiar__c</fullName>
        <label>Total a Financiar</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/Marcas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>800</fullName>
        <label>ALFA ROMEO</label>
    </customValue>
    <customValue>
        <fullName>801</fullName>
        <label>AUDI</label>
    </customValue>
    <customValue>
        <fullName>802</fullName>
        <label>BAIC</label>
    </customValue>
    <customValue>
        <fullName>BENELLI</fullName>
    </customValue>
    <customValue>
        <fullName>BENTLEY</fullName>
    </customValue>
    <customValue>
        <fullName>803</fullName>
        <label>BMW</label>
    </customValue>
    <customValue>
        <fullName>804</fullName>
        <label>BRILLIANCE</label>
    </customValue>
    <customValue>
        <fullName>805</fullName>
        <label>BYD</label>
    </customValue>
    <customValue>
        <fullName>806</fullName>
        <label>CHANGAN</label>
    </customValue>
    <customValue>
        <fullName>807</fullName>
        <label>CHERY</label>
    </customValue>
    <customValue>
        <fullName>808</fullName>
        <label>CHEVROLET</label>
    </customValue>
    <customValue>
        <fullName>809</fullName>
        <label>CHRYSLER</label>
    </customValue>
    <customValue>
        <fullName>810</fullName>
        <label>CITROËN</label>
    </customValue>
    <customValue>
        <fullName>812</fullName>
        <label>DAIHATSU</label>
    </customValue>
    <customValue>
        <fullName>813</fullName>
        <label>DFM</label>
    </customValue>
    <customValue>
        <fullName>814</fullName>
        <label>DFSK</label>
    </customValue>
    <customValue>
        <fullName>815</fullName>
        <label>DODGE</label>
    </customValue>
    <customValue>
        <fullName>DONG FENG</fullName>
    </customValue>
    <customValue>
        <fullName>DS</fullName>
    </customValue>
    <customValue>
        <fullName>816</fullName>
        <label>FAW</label>
    </customValue>
    <customValue>
        <fullName>FERRARI</fullName>
    </customValue>
    <customValue>
        <fullName>817</fullName>
        <label>FIAT</label>
    </customValue>
    <customValue>
        <fullName>818</fullName>
        <label>FORD</label>
    </customValue>
    <customValue>
        <fullName>FOTON</fullName>
    </customValue>
    <customValue>
        <fullName>FUSO</fullName>
    </customValue>
    <customValue>
        <fullName>GAC</fullName>
    </customValue>
    <customValue>
        <fullName>GAC GONOW</fullName>
    </customValue>
    <customValue>
        <fullName>819</fullName>
        <label>GEELY</label>
    </customValue>
    <customValue>
        <fullName>820</fullName>
        <label>GREAT WALL</label>
    </customValue>
    <customValue>
        <fullName>GREAT WALL MOTORS</fullName>
    </customValue>
    <masterLabel>Marcas</masterLabel>
</GlobalValueSet>

Amicar/src/classes/AMICAR_desmarcaUltimoEventoTest.cls
@isTest
public class AMICAR_desmarcaUltimoEventoTest {
    @isTest
    private static void test01(){
        RecordType registro = [select id, name from recordType where name='Credito Renovaciones'];
        RecordType regCuenta = [select id, name from recordType where name='Cliente Persona'];
        Account account = new Account(        
            LastName = 'Norambuena',
            FirstName = 'Marcelo',
            Salutation = 'Mr.',
            RecordTypeId = regCuenta.Id,
            ShippingStreet = 'Rogelio Ugarte 1746',
            ShippingCity = 'Santiago',
            ShippingCountry = 'Chile',
            PersonMobilePhone = '+56983537065',
            PersonEmail = 'mnorambuena@nectia.com',
            PersonHasOptedOutOfEmail = true,
            PersonDoNotCall = true,
            Situaci_n_Laboral__c = 'Trabajando',
            N_10__c = false,
            N_111__c = false,
            N_11__c = false,
            N_1__c = true,
            N_2__c = false,
            N_3__c = false,
            N_4__c = false,
            N_5__c = false,
            N_6__c = false,
            N_7__c = false,
            N_8__c = false,
            N_9__c = false,
            N_mes_en_curso__c = false,
            N_mes_vencimiento_posterior__c = false,
            RUT__c = '18874834-1',
            et4ae5__HasOptedOutOfMobile__pc = false,
            et4ae5__Mobile_Country_Code__pc = 'US',
            Fecha_de_ingreso__pc = Date.newInstance(2020,03,02),
            Renta__pc = 600000.0,
            Empleador__pc = 'Nectia',
            Cargo__pc = 'Consultor');
        insert account;
        
        Asset asset = new Asset(
            AccountId = account.id,
            IsCompetitorProduct = false,
            Name = 'Credito1Prueba',
            SerialNumber = '0123456789',
            RecordTypeId = registro.Id,
            Fecha_de_Vencimiento_Cuoton__c = Date.newInstance(2020,04,30),
            Nombre_EF__c = 'CMR FALABELLA',
            Concesionario__c = '69',
            Egresos__c = 100000.0,
            Estado_Cierre__c = 'VIGENTE',
            Estado_Solicitud__c = 'APROBADA',
            Estado_cr_dito__c = 'PREPAGADO',
            Fecha_ingreso_empleo__c = Date.newInstance(2020,03,11),
            Fecha_ltima_Cuota__c = Date.newInstance(2020,06,19),
            Id_Credito__c = '700293',
            Importadores__c = '829957000',
            Local__c = '2 ANFRUNS SANTIAGO',
            Marca_Veh_culo__c = 'MAZDA',
            Respuesta_EF__c = 'Preaprobado',
            Sueldo_Liquido__c = 600000.0,
            Tipo_de_Contrato__c = 'Plazo Fijo',
            Tipo_de_Credito__c = 'Compra Inteligente',
            Total_a_Financiar__c = 1000000.0,
            EF_Original__c = 'Santander',
            Ejecutivo_Call__c = 'Jocelyn Umaña',
            Preevaluacion_EF__c = 'Preaprobado',
            Fecha_Hora_Ultimo_Evento__c = DateTime.newInstance(2020,6,5,20,1219,73190));
        insert asset;
       
            RecordType regEvent=[select id,name from recordType where name='Evento Renovaciones'];
        Event event = new Event(
            Subject ='Prueba Evento Desarrollo',
            Estado_de_Actividad__c = 'CONTACTADO',
            StartDateTime = DateTime.newInstance(2020,6,5,20,1219,73190),
            EndDateTime = DateTime.newInstance(2020,6,6,20,1219,73190),
            WhatId = asset.id,
            RecordTypeId=regEvent.Id);
        insert event;
         Event event2 = new Event(
            Subject ='Prueba Evento Desarrollo',
            Estado_de_Actividad__c = 'CONTACTADO',
            StartDateTime = DateTime.newInstance(2020,6,5,20,1219,73190),
            EndDateTime = DateTime.newInstance(2020,6,6,20,1219,73190),
            WhatId = asset.id,
            RecordTypeId=regEvent.Id);
        insert event2;
        List<Event> listaEventos=new List<Event>();
        listaEventos.add(event2);
        AMICAR_desmarcaUltimoEvento.desmarcaCheck(listaEventos);

        
    }
    
}