src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RUT__c</fullName>
        <externalId>true</externalId>
        <label>RUT</label>
        <length>11</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Amicar/src/objects/Modelo_de_vehiculo__c.object
<CustomObject>
    <fields>
        <fullName>Modelo__c</fullName>
        <label>Modelo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Modelo de vehículo</label>
    <nameField>
        <label>Modelo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modelos de vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>A_o_Veh_culo__c</fullName>
        <label>Año Vehículo</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ConteoCarta__c</fullName>
        <label>ConteoCarta</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cuenta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cuenta</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cuotas__c</fullName>
        <label>Cuotas</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entidad_Financiera__c</fullName>
        <label>Entidad Financiera</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Entidades_Financieras</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Id_Solicitud__c</fullName>
        <externalId>true</externalId>
        <label>Id Solicitud</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Importadora__c</fullName>
        <label>Importadora</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Importadores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Locales__c</fullName>
        <label>Locales</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Concesionarios__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Locales</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Marca_vehiculo__c</fullName>
        <label>Marca vehículo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Marcas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Modelo2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modelo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Modelo_de_vehiculo__c.Marca__c</field>
                <operation>equals</operation>
                <valueField>$Source.Marca_vehiculo__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Modelo_de_vehiculo__c</referenceTo>
        <relationshipLabel>Oportunidades</relationshipLabel>
        <relationshipName>Oportunidades</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modelo__c</fullName>
        <label>Modelo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pie__c</fullName>
        <label>Pie</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Precio_vehiculo__c</fullName>
        <label>Precio vehículo</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RUT__c</fullName>
        <formula>Account.RUT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RUT</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Saldo_precio__c</fullName>
        <formula>Precio_vehiculo__c - (Pie__c + Monto_retoma__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Saldo precio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tasa__c</fullName>
        <label>Tasa</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tipo_de_Veh_culo__c</fullName>
        <label>Tipo de Vehículo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                </value>
                <value>
                    <fullName>Usado</fullName>
                </value>
                <value>
                    <fullName>NU</fullName>
                    <label>Particular Nuevo</label>
                </value>
                <value>
                    <fullName>NP</fullName>
                    <label>Comercial Nuevo</label>
                </value>
                <value>
                    <fullName>US</fullName>
                    <label>Particular Usado</label>
                </value>
                <value>
                    <fullName>UP</fullName>
                    <label>Comercial Usado</label>
                </value>
                <value>
                    <fullName>NM</fullName>
                    <label>Maquinaria Pesada Nuevas</label>
                </value>
                <value>
                    <fullName>UM</fullName>
                    <label>Maquinaria Pesada Usadas</label>
                </value>
                <value>
                    <fullName>NT</fullName>
                    <label>Motos Nuevas</label>
                </value>
                <value>
                    <fullName>UT</fullName>
                    <label>Motos Usadas</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <label>Version</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Comisi_n_dealer__c</fullName>
        <label>Comisión dealer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cuotas__c</fullName>
        <label>Cuotas</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Modelo__c</fullName>
        <label>Modelo</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pie__c</fullName>
        <label>Pie</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Saldo_precio__c</fullName>
        <label>Saldo precio</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tasa__c</fullName>
        <label>Tasa</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Marcas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>800</fullName>
        <label>ALFA ROMEO</label>
    </customValue>
    <customValue>
        <fullName>801</fullName>
        <label>AUDI</label>
    </customValue>
    <customValue>
        <fullName>802</fullName>
        <label>BAIC</label>
    </customValue>
    <customValue>
        <fullName>BENELLI</fullName>
    </customValue>
    <customValue>
        <fullName>BENTLEY</fullName>
    </customValue>
    <customValue>
        <fullName>803</fullName>
        <label>BMW</label>
    </customValue>
    <customValue>
        <fullName>804</fullName>
        <label>BRILLIANCE</label>
    </customValue>
    <customValue>
        <fullName>805</fullName>
        <label>BYD</label>
    </customValue>
    <customValue>
        <fullName>806</fullName>
        <label>CHANGAN</label>
    </customValue>
    <customValue>
        <fullName>807</fullName>
        <label>CHERY</label>
    </customValue>
    <customValue>
        <fullName>808</fullName>
        <label>CHEVROLET</label>
    </customValue>
    <customValue>
        <fullName>809</fullName>
        <label>CHRYSLER</label>
    </customValue>
    <customValue>
        <fullName>810</fullName>
        <label>CITROËN</label>
    </customValue>
    <customValue>
        <fullName>812</fullName>
        <label>DAIHATSU</label>
    </customValue>
    <customValue>
        <fullName>813</fullName>
        <label>DFM</label>
    </customValue>
    <customValue>
        <fullName>814</fullName>
        <label>DFSK</label>
    </customValue>
    <customValue>
        <fullName>815</fullName>
        <label>DODGE</label>
    </customValue>
    <customValue>
        <fullName>DONG FENG</fullName>
    </customValue>
    <customValue>
        <fullName>DS</fullName>
    </customValue>
    <customValue>
        <fullName>816</fullName>
        <label>FAW</label>
    </customValue>
    <customValue>
        <fullName>FERRARI</fullName>
    </customValue>
    <customValue>
        <fullName>817</fullName>
        <label>FIAT</label>
    </customValue>
    <customValue>
        <fullName>818</fullName>
        <label>FORD</label>
    </customValue>
    <customValue>
        <fullName>FOTON</fullName>
    </customValue>
    <customValue>
        <fullName>FUSO</fullName>
    </customValue>
    <customValue>
        <fullName>GAC</fullName>
    </customValue>
    <customValue>
        <fullName>GAC GONOW</fullName>
    </customValue>
    <customValue>
        <fullName>819</fullName>
        <label>GEELY</label>
    </customValue>
    <customValue>
        <fullName>820</fullName>
        <label>GREAT WALL</label>
    </customValue>
    <customValue>
        <fullName>GREAT WALL MOTORS</fullName>
    </customValue>
    <masterLabel>Marcas</masterLabel>
</GlobalValueSet>

src/classes/AMICAR_CartaAdjudicacionController.cls
public with sharing class AMICAR_CartaAdjudicacionController {

    private sObject mysObject;

    public List<Opportunity> solicitudCarta {get;set;}
    public List<Quote> solicitudSimulacion {get;set;}
    public List<Remate__c> solicitudRemate {get;set;}
    public List<User> solicitudUsuario {get;set;}
    public List<Relacion__c> solicitudCompraPara {get;set;}
    public String fechaDia {get;set;}

    public String idSolicitud{get;set;}


    public void AMICAR_CartaAdjudicacionController(ApexPages.StandardController controller) {
        
    }

    public PageReference cargaDatos(){

        idSolicitud = ApexPages.currentPage().getParameters().get('id');
        System.debug('id->'+idSolicitud);

        solicitudCarta = [SELECT Id,OwnerId,A_o_Veh_culo__c,toLabel(Marca_vehiculo__c),Modelo__c,Modelo2__r.Name,Version__c,Precio_vehiculo__c,Pie__c,Saldo_precio__c,toLabel(Tipo_de_Veh_culo__c),Tasa__c,Id_Solicitud__c,Account.Name,RUT__c,toLabel(Importadora__c),toLabel(Locales__c),ConteoCarta__c,Cuotas__c  FROM Opportunity WHERE Id =: idSolicitud];
        System.debug('carta->'+solicitudCarta);

        solicitudSimulacion = [SELECT Id,Comisi_n_dealer__c FROM Quote WHERE OpportunityId =: idSolicitud AND IsSyncing = true];
        System.debug('escenario->'+solicitudSimulacion);

        solicitudRemate = [SELECT Id,toLabel(Entidad_Financiera__c) FROM Remate__c WHERE Solicitud__c =: idSolicitud AND Ganadora__c = true];
        System.debug('remate->'+solicitudRemate);

        solicitudUsuario = [SELECT Id,Name,Email FROM User WHERE Id =: solicitudCarta[0].OwnerId];
        System.debug('usuario->'+solicitudUsuario);
        
        solicitudCompraPara = [SELECT Id,Cuenta__r.Name,Cuenta__r.RUT__c  FROM Relacion__c WHERE Solicitud__c =: idSolicitud AND RecordType.DeveloperName =: 'Compra_para'];
        System.debug('solicitudCompraPara->'+solicitudCompraPara);
        fechaDia = String.valueOf(Datetime.newInstance(System.today().year(), System.today().month(), System.today().day()).format('dd-MM-yyyy'));

        return null;
    }
}