src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Locales__c</fullName>
        <label>Locales</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Locales</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>carBrandDescription__c</fullName>
        <label>Marca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Marcas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>carBrandId__c</fullName>
        <label>Marca del Vehiculo número</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>carModelDescription__c</fullName>
        <label>Modelo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>carModelId__c</fullName>
        <label>Modelo Numero</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>carPrice__c</fullName>
        <label>Valor Vehículo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>carVersion__c</fullName>
        <label>Versión</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>carYear__c</fullName>
        <label>Año Vehículo</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>channelId__c</fullName>
        <label>Canal</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>channel__c</fullName>
        <label>Nombre Canal</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Autopia</fullName>
                </value>
                <value>
                    <fullName>Automarket</fullName>
                </value>
                <value>
                    <fullName>Destacame</fullName>
                </value>
                <value>
                    <fullName>amicar</fullName>
                </value>
                <value>
                    <fullName>Dercousados</fullName>
                </value>
                <value>
                    <fullName>Autofaro</fullName>
                </value>
                <value>
                    <fullName>MERCADOLIBRE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>downPaymentPercentage__c</fullName>
        <label>Pie %</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>downPayment__c</fullName>
        <label>Monto Pie</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>engine__c</fullName>
        <label>Motor de Evaluación</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amicar.cl</fullName>
                    <default>true</default>
                    <label>Amicar.cl</label>
                </value>
                <value>
                    <fullName>Autopia</fullName>
                </value>
                <value>
                    <fullName>DercoUsados</fullName>
                </value>
                <value>
                    <fullName>Destacame</fullName>
                </value>
                <value>
                    <fullName>Platanus</fullName>
                </value>
                <value>
                    <fullName>AutoMarket</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>evaluationResult__c</fullName>
        <label>Estado Evaluación Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equifax Rechaza</fullName>
                </value>
                <value>
                    <fullName>Equifax Aprueba</fullName>
                </value>
                <value>
                    <fullName>Autofin</fullName>
                </value>
                <value>
                    <fullName>Tanner</fullName>
                </value>
                <value>
                    <fullName>Sin respuesta</fullName>
                </value>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>RECHAZADO</fullName>
                    <label>Rechazado</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>importer__c</fullName>
        <label>Importadora</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Importadores</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>income__c</fullName>
        <label>Renta Líquida</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>loanSetting__c</fullName>
        <label>Escenario Interés</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>loanType__c</fullName>
        <label>Tipo Crédito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OI</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>monthlyPayment__c</fullName>
        <label>Valor Cuota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>monthsWorked__c</fullName>
        <label>Antigüedad Laboral</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>motherLastName__c</fullName>
        <label>Apellido Materno</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>productCode__c</fullName>
        <label>Código Producto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rut__c</fullName>
        <label>RUT</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>salesChannel__c</fullName>
        <label>Concesionarios</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>importer__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Concesionario</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Sub-Estado</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>Solicita nuevo contacto</fullName>
                </value>
                <value>
                    <fullName>No Contactado</fullName>
                </value>
                <value>
                    <fullName>Datos Erróneos</fullName>
                </value>
                <value>
                    <fullName>Desistido</fullName>
                </value>
                <value>
                    <fullName>Adjudicado</fullName>
                </value>
                <value>
                    <fullName>No Adjudicado</fullName>
                </value>
                <value>
                    <fullName>Solicitud de Crédito</fullName>
                </value>
                <value>
                    <fullName>Evaluación con EEFF</fullName>
                </value>
                <value>
                    <fullName>Replanteamiento Solicitud de Crédito</fullName>
                </value>
                <value>
                    <fullName>Solicitud de Documentación</fullName>
                </value>
                <value>
                    <fullName>Envío de Documentación</fullName>
                </value>
                <value>
                    <fullName>Carta de Aprobación</fullName>
                </value>
                <value>
                    <fullName>Agendamiento Cita en Local</fullName>
                </value>
                <value>
                    <fullName>Reagendamiento Cita en Local</fullName>
                </value>
                <value>
                    <fullName>Derivado a Local</fullName>
                </value>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Condicionado</fullName>
                </value>
                <value>
                    <fullName>Agendado</fullName>
                    <isActive>false</isActive>
                    <label>Agendado</label>
                </value>
                <value>
                    <fullName>Asiste a Concesionario</fullName>
                    <isActive>false</isActive>
                    <label>Asiste a Concesionario</label>
                </value>
                <value>
                    <fullName>En Contactabilidad</fullName>
                    <isActive>false</isActive>
                    <label>En Contactabilidad</label>
                </value>
                <value>
                    <fullName>No Asiste a Concesionario</fullName>
                    <isActive>false</isActive>
                    <label>No Asiste a Concesionario</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>termDescription__c</fullName>
        <label>Plazo Crédito</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>terms__c</fullName>
        <label>Nº de Cuotas</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
                <value>
                    <fullName>48</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>transactionDate__c</fullName>
        <label>Fecha Transacción</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>transactionId__c</fullName>
        <label>ID Transacción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transactionTime__c</fullName>
        <label>Hora Transacción</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>tripletId__c</fullName>
        <label>Id Tripleta</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vehicleType__c</fullName>
        <label>Tipo de Vehículo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                </value>
                <value>
                    <fullName>Usado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>workType__c</fullName>
        <label>Situación Laboral</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/globalValueSets/Marcas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>800</fullName>
        <label>ALFA ROMEO</label>
    </customValue>
    <customValue>
        <fullName>801</fullName>
        <label>AUDI</label>
    </customValue>
    <customValue>
        <fullName>802</fullName>
        <label>BAIC</label>
    </customValue>
    <customValue>
        <fullName>BENELLI</fullName>
    </customValue>
    <customValue>
        <fullName>BENTLEY</fullName>
    </customValue>
    <customValue>
        <fullName>803</fullName>
        <label>BMW</label>
    </customValue>
    <customValue>
        <fullName>804</fullName>
        <label>BRILLIANCE</label>
    </customValue>
    <customValue>
        <fullName>805</fullName>
        <label>BYD</label>
    </customValue>
    <customValue>
        <fullName>806</fullName>
        <label>CHANGAN</label>
    </customValue>
    <customValue>
        <fullName>807</fullName>
        <label>CHERY</label>
    </customValue>
    <customValue>
        <fullName>808</fullName>
        <label>CHEVROLET</label>
    </customValue>
    <customValue>
        <fullName>809</fullName>
        <label>CHRYSLER</label>
    </customValue>
    <customValue>
        <fullName>810</fullName>
        <label>CITROËN</label>
    </customValue>
    <customValue>
        <fullName>812</fullName>
        <label>DAIHATSU</label>
    </customValue>
    <customValue>
        <fullName>813</fullName>
        <label>DFM</label>
    </customValue>
    <customValue>
        <fullName>814</fullName>
        <label>DFSK</label>
    </customValue>
    <customValue>
        <fullName>815</fullName>
        <label>DODGE</label>
    </customValue>
    <customValue>
        <fullName>DONG FENG</fullName>
    </customValue>
    <customValue>
        <fullName>DS</fullName>
    </customValue>
    <customValue>
        <fullName>816</fullName>
        <label>FAW</label>
    </customValue>
    <customValue>
        <fullName>FERRARI</fullName>
    </customValue>
    <customValue>
        <fullName>817</fullName>
        <label>FIAT</label>
    </customValue>
    <customValue>
        <fullName>818</fullName>
        <label>FORD</label>
    </customValue>
    <customValue>
        <fullName>FOTON</fullName>
    </customValue>
    <customValue>
        <fullName>FUSO</fullName>
    </customValue>
    <customValue>
        <fullName>GAC</fullName>
    </customValue>
    <customValue>
        <fullName>GAC GONOW</fullName>
    </customValue>
    <customValue>
        <fullName>819</fullName>
        <label>GEELY</label>
    </customValue>
    <customValue>
        <fullName>820</fullName>
        <label>GREAT WALL</label>
    </customValue>
    <customValue>
        <fullName>GREAT WALL MOTORS</fullName>
    </customValue>
    <masterLabel>Marcas</masterLabel>
</GlobalValueSet>

Amicar/src/classes/AMICAR_copyLeadsWSTest.cls
/**********************************************************************************
Desarrollado por: Cloud Solutions
Autor: Esteban Flores (EF)
Proyecto: Amicar
Descripción: Clase Test para integraciones
---------------------------------------------------------------------------------
No. Fecha                Autor                     Descripción
------ ---------- ---------------------------------------------------------------
1.0 12-02-2020            EF                   Creación de la Clase.
***********************************************************************************/
@isTest
public class AMICAR_copyLeadsWSTest{
    @testSetup static void setup(){
        Lead leadA = new Lead();
        leadA.transactionId__c = '1010101';
        leadA.channel__c = '0831201';
        leadA.engine__c = '012039123918';
        leadA.evaluationResult__c = '12';
        leadA.transactionDate__c = System.today();
        leadA.transactionTime__c = datetime.now().time();
        leadA.rut__c = '1-9';
        leadA.FirstName = 'Testing A';
        leadA.lastName = 'Prueba A';
        leadA.motherLastName__c = 'Perez';
        leadA.income__c = 1000;
        leadA.Email = 'test@test.cl';
        leadA.Phone = '1239123191';
        leadA.carPrice__c = 1000;
        leadA.downPayment__c = 12;
        leadA.vehicleType__c = 'Usado';
        leadA.workType__c = 'Hot';
        leadA.carBrandId__c = 12;   
        leadA.carBrandDescription__c = 'SUZUKI';
        leadA.carModelId__c = 12;
        leadA.carModelDescription__c = 'Descripcion Modelo';
        leadA.carVersion__c = 'Sport';
        leadA.monthlyPayment__c = 1;
        leadA.tripletId__c = '10';
        leadA.carYear__c = '2014';
        leadA.loanSetting__c = 'Plop';
        leadA.channelId__c = 'Autopia';
        leadA.importer__c = 'DERCO S.A.';
        leadA.salesChannel__c = 'VIRTUAL';
        leadA.Locales__c = '';
        leadA.Company = 'Compañia';
        leadA.monthsWorked__c = 10;
        leadA.termDescription__c = 'Descripcion Terminos';
        leadA.productCode__c = '10001';
        leadA.loanType__c = 'Validacion';
        leadA.downPaymentPercentage__c = 90;
        leadA.terms__c = 'Terminos';
        leadA.status = 'Nuevo';
        leadA.status__c = 'Nuevo';
        insert leadA;
        Lead leadB = new Lead();
        leadB.FirstName = 'Testing B';
        leadB.lastName = 'Prueba 2';
        leadB.status = 'Nuevo';
        leadB.status__c = 'Nuevo';
        insert leadB;
    }
    @isTest static void testCotizadorLoadData() {
        Lead x = [SELECT Id, carYear__c, MobilePhone FROM Lead WHERE rut__c = '1-9'];
        AMICAR_copyLeadsWS y = new AMICAR_copyLeadsWS(x.Id);
        List<Id> ids = new List<Id>();
        ids.add(x.Id);
        AMICAR_copyLeadsWS.CopiaLeads(ids);
        AMICAR_CopyLeadsWSJSON testData = new AMICAR_CopyLeadsWSJSON();
        System.debug(testdata);
        System.debug(AMICAR_CopyLeadsWSJSON.testJSON());
        AMICAR_CopyLeadsWSJSON.parse(AMICAR_CopyLeadsWSJSON.testJSON());
        x.carYear__c = '2020';
        x.MobilePhone = '22223344';
        update x;
        x.Phone = '23123123';
        x.MobilePhone = '';
        update x;
    }
}