src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Locales__c</fullName>
        <label>Locales</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Locales</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>carBrandDescription__c</fullName>
        <label>Marca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Marcas</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>carBrandId__c</fullName>
        <label>Marca del Vehiculo número</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>carModelDescription__c</fullName>
        <label>Modelo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>carModelId__c</fullName>
        <label>Modelo Numero</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>carPrice__c</fullName>
        <label>Valor Vehículo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>carVersion__c</fullName>
        <label>Versión</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>carYear__c</fullName>
        <label>Año Vehículo</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>channelId__c</fullName>
        <label>Canal</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>channel__c</fullName>
        <label>Nombre Canal</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Autopia</fullName>
                </value>
                <value>
                    <fullName>Automarket</fullName>
                </value>
                <value>
                    <fullName>Destacame</fullName>
                </value>
                <value>
                    <fullName>amicar</fullName>
                </value>
                <value>
                    <fullName>Dercousados</fullName>
                </value>
                <value>
                    <fullName>Autofaro</fullName>
                </value>
                <value>
                    <fullName>MERCADOLIBRE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>downPaymentPercentage__c</fullName>
        <label>Pie %</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>downPayment__c</fullName>
        <label>Monto Pie</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>engine__c</fullName>
        <label>Motor de Evaluación</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Amicar.cl</fullName>
                    <default>true</default>
                    <label>Amicar.cl</label>
                </value>
                <value>
                    <fullName>Autopia</fullName>
                </value>
                <value>
                    <fullName>DercoUsados</fullName>
                </value>
                <value>
                    <fullName>Destacame</fullName>
                </value>
                <value>
                    <fullName>Platanus</fullName>
                </value>
                <value>
                    <fullName>AutoMarket</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>evaluationResult__c</fullName>
        <label>Estado Evaluación Comercial</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Equifax Rechaza</fullName>
                </value>
                <value>
                    <fullName>Equifax Aprueba</fullName>
                </value>
                <value>
                    <fullName>Autofin</fullName>
                </value>
                <value>
                    <fullName>Tanner</fullName>
                </value>
                <value>
                    <fullName>Sin respuesta</fullName>
                </value>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>RECHAZADO</fullName>
                    <label>Rechazado</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>income__c</fullName>
        <label>Renta Líquida</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>loanSetting__c</fullName>
        <label>Escenario Interés</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>loanType__c</fullName>
        <label>Tipo Crédito</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>OI</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>monthlyPayment__c</fullName>
        <label>Valor Cuota</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>monthsWorked__c</fullName>
        <label>Antigüedad Laboral</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>motherLastName__c</fullName>
        <label>Apellido Materno</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>productCode__c</fullName>
        <label>Código Producto</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rut__c</fullName>
        <label>RUT</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>salesChannel__c</fullName>
        <label>Concesionarios</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>importer__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Concesionario</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>Sub-Estado</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                    <default>true</default>
                    <label>Nuevo</label>
                </value>
                <value>
                    <fullName>Solicita nuevo contacto</fullName>
                </value>
                <value>
                    <fullName>No Contactado</fullName>
                </value>
                <value>
                    <fullName>Datos Erróneos</fullName>
                </value>
                <value>
                    <fullName>Desistido</fullName>
                </value>
                <value>
                    <fullName>Adjudicado</fullName>
                </value>
                <value>
                    <fullName>No Adjudicado</fullName>
                </value>
                <value>
                    <fullName>Solicitud de Crédito</fullName>
                </value>
                <value>
                    <fullName>Evaluación con EEFF</fullName>
                </value>
                <value>
                    <fullName>Replanteamiento Solicitud de Crédito</fullName>
                </value>
                <value>
                    <fullName>Solicitud de Documentación</fullName>
                </value>
                <value>
                    <fullName>Envío de Documentación</fullName>
                </value>
                <value>
                    <fullName>Carta de Aprobación</fullName>
                </value>
                <value>
                    <fullName>Agendamiento Cita en Local</fullName>
                </value>
                <value>
                    <fullName>Reagendamiento Cita en Local</fullName>
                </value>
                <value>
                    <fullName>Derivado a Local</fullName>
                </value>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Condicionado</fullName>
                </value>
                <value>
                    <fullName>Agendado</fullName>
                    <isActive>false</isActive>
                    <label>Agendado</label>
                </value>
                <value>
                    <fullName>Asiste a Concesionario</fullName>
                    <isActive>false</isActive>
                    <label>Asiste a Concesionario</label>
                </value>
                <value>
                    <fullName>En Contactabilidad</fullName>
                    <isActive>false</isActive>
                    <label>En Contactabilidad</label>
                </value>
                <value>
                    <fullName>No Asiste a Concesionario</fullName>
                    <isActive>false</isActive>
                    <label>No Asiste a Concesionario</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>termDescription__c</fullName>
        <label>Plazo Crédito</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>terms__c</fullName>
        <label>Nº de Cuotas</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
                <value>
                    <fullName>48</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>transactionDate__c</fullName>
        <label>Fecha Transacción</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>transactionId__c</fullName>
        <label>ID Transacción</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transactionTime__c</fullName>
        <label>Hora Transacción</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>tripletId__c</fullName>
        <label>Id Tripleta</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vehicleType__c</fullName>
        <label>Tipo de Vehículo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nuevo</fullName>
                </value>
                <value>
                    <fullName>Usado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>workPhone__c</fullName>
        <label>Fono Comercial</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>workType__c</fullName>
        <label>Situación Laboral</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/globalValueSets/Marcas.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>800</fullName>
        <label>ALFA ROMEO</label>
    </customValue>
    <customValue>
        <fullName>801</fullName>
        <label>AUDI</label>
    </customValue>
    <customValue>
        <fullName>802</fullName>
        <label>BAIC</label>
    </customValue>
    <customValue>
        <fullName>BENELLI</fullName>
    </customValue>
    <customValue>
        <fullName>BENTLEY</fullName>
    </customValue>
    <customValue>
        <fullName>803</fullName>
        <label>BMW</label>
    </customValue>
    <customValue>
        <fullName>804</fullName>
        <label>BRILLIANCE</label>
    </customValue>
    <customValue>
        <fullName>805</fullName>
        <label>BYD</label>
    </customValue>
    <customValue>
        <fullName>806</fullName>
        <label>CHANGAN</label>
    </customValue>
    <customValue>
        <fullName>807</fullName>
        <label>CHERY</label>
    </customValue>
    <customValue>
        <fullName>808</fullName>
        <label>CHEVROLET</label>
    </customValue>
    <customValue>
        <fullName>809</fullName>
        <label>CHRYSLER</label>
    </customValue>
    <customValue>
        <fullName>810</fullName>
        <label>CITROËN</label>
    </customValue>
    <customValue>
        <fullName>812</fullName>
        <label>DAIHATSU</label>
    </customValue>
    <customValue>
        <fullName>813</fullName>
        <label>DFM</label>
    </customValue>
    <customValue>
        <fullName>814</fullName>
        <label>DFSK</label>
    </customValue>
    <customValue>
        <fullName>815</fullName>
        <label>DODGE</label>
    </customValue>
    <customValue>
        <fullName>DONG FENG</fullName>
    </customValue>
    <customValue>
        <fullName>DS</fullName>
    </customValue>
    <customValue>
        <fullName>816</fullName>
        <label>FAW</label>
    </customValue>
    <customValue>
        <fullName>FERRARI</fullName>
    </customValue>
    <customValue>
        <fullName>817</fullName>
        <label>FIAT</label>
    </customValue>
    <customValue>
        <fullName>818</fullName>
        <label>FORD</label>
    </customValue>
    <customValue>
        <fullName>FOTON</fullName>
    </customValue>
    <customValue>
        <fullName>FUSO</fullName>
    </customValue>
    <customValue>
        <fullName>GAC</fullName>
    </customValue>
    <customValue>
        <fullName>GAC GONOW</fullName>
    </customValue>
    <customValue>
        <fullName>819</fullName>
        <label>GEELY</label>
    </customValue>
    <customValue>
        <fullName>820</fullName>
        <label>GREAT WALL</label>
    </customValue>
    <customValue>
        <fullName>GREAT WALL MOTORS</fullName>
    </customValue>
    <masterLabel>Marcas</masterLabel>
</GlobalValueSet>

src/classes/AMICAR_copyLeadsWS.cls
/**********************************************************************************
Desarrollado por: Cloud Solutions
Autor: Esteban Flores (EF)
Proyecto: Amicar
Descripción: Clase controladora para copia de Leads por integracion
---------------------------------------------------------------------------------
No. Fecha                Autor                     Descripción
------ ---------- ---------------------------------------------------------------
1.0 02-02-2020            EF                   Creación de la Clase.
***********************************************************************************/
public class AMICAR_copyLeadsWS{
    public AMICAR_copyLeadsWS(Id iLead){
        Lead myLead = [SELECT Id, transactionId__c, channel__c, engine__c, evaluationResult__c, transactionDate__c, 
                    transactionTime__c, rut__c, FirstName, lastName, motherLastName__c, income__c, Email, 
                    carPrice__c, downPayment__c, vehicleType__c, workType__c, carBrandId__c, carBrandDescription__c, 
                    carModelId__c, carModelDescription__c, carVersion__c, monthlyPayment__c, tripletId__c, carYear__c, 
                    loanSetting__c, channelId__c, salesChannel__c, Locales__c, Company, monthsWorked__c, termDescription__c, 
                    productCode__c, loanType__c, downPaymentPercentage__c, terms__c, status, status__c, MobilePhone, Phone, workPhone__c
                 FROM Lead
                 WHERE Id =: iLead];
    }

    @InvocableMethod(label='Copiar Lead' description='Copia Leads en base de datos replica')
    public static List<String> CopiaLeads (List<String> iLead) {
        Lead lead = [SELECT Id, transactionId__c, channel__c, engine__c, evaluationResult__c, transactionDate__c, 
                    transactionTime__c, rut__c, FirstName, lastName, motherLastName__c, income__c, Email,
                    carPrice__c, downPayment__c, vehicleType__c, workType__c, carBrandId__c, carBrandDescription__c, 
                    carModelId__c, carModelDescription__c, carVersion__c, monthlyPayment__c, tripletId__c, carYear__c, 
                    loanSetting__c, channelId__c, salesChannel__c, Locales__c, Company, monthsWorked__c, termDescription__c, 
                    productCode__c, loanType__c, downPaymentPercentage__c, terms__c, status, status__c, MobilePhone, Phone, workPhone__c
                 FROM Lead
                 WHERE Id =: iLead];
        String json = AMICAR_copyLeadsWS.loadRequest(lead);
        callService(json, lead.Id);
        return null;
    }

    @future(callout=true)
    static void callService(String json, String idLead){
        HttpRequest request = new HttpRequest();
        HttpResponse response = new HttpResponse();
        //Para chequear si es sandbox o productivo
        Organization ox = [SELECT Id, IsSandbox FROM Organization LIMIT 1];
        String endP = '';
        try{
            //Obtener endpoint de metadata
            endP = [SELECT URL__c
                    FROM AMICAR_Integracion__mdt
                    WHERE MasterLabel = 'Leads'].URL__c;
            request.setEndpoint(endP+'?IdSended='+idLead);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setBody(json);
            System.debug(json);
            if (!Test.IsRunningTest()){
                Http http = new Http();
                response = http.send(request);
            }else{
                String falseJson = AMICAR_CopyLeadsWSJSON.testJSON();
                response.setBody(falseJson);
            }
            System.debug('Body de respuesta: '+response.getBody());
        }catch(Exception e){
            System.debug('Tipo de excepción: ' + e.getTypeName());
            System.debug('Mensaje: ' + e.getMessage());
            System.debug('Causa: ' + e.getCause());
            System.debug('Línea: ' + e.getLineNumber());
            System.debug('Traza: ' + e.getStackTraceString());
        }
    }

    public static String loadRequest(Lead myLead){
        /* Llenar datos con información del lead */
        AMICAR_CopyLeadsWSJSON objToJSON = new AMICAR_CopyLeadsWSJSON();
        objToJSON.idTransaccion = myLead.transactionId__c != null?myLead.transactionId__c:'';
        objToJSON.Contador = '1';
        objToJSON.nombreCanal = myLead.channel__c != null?myLead.channel__c:'';
        objToJSON.nombreMotor = myLead.engine__c != null?myLead.engine__c:'';
        objToJSON.nombreOperaciones = '';
        objToJSON.respuestaAPI = myLead.evaluationResult__c != null?myLead.evaluationResult__c:'';
        if(myLead.transactionDate__c != null){
            String fecha = String.valueOf(myLead.transactionDate__c.year())+'-';
            if(myLead.transactionDate__c.month() < 10){
                fecha = fecha + '0'+String.valueOf(myLead.transactionDate__c.month())+'-';
            }else{
                fecha = fecha + String.valueOf(myLead.transactionDate__c.month())+'-';
            }
            if(myLead.transactionDate__c.day() < 10){
                fecha = fecha + '0'+String.valueOf(myLead.transactionDate__c.day());
            }else{
                fecha = fecha + String.valueOf(myLead.transactionDate__c.day());
            }
            objToJSON.FechaTransaccion = fecha;
        }else{
            objToJSON.FechaTransaccion = null;
        }
        if(myLead.transactionTime__c != null){
            String hora = String.valueOf(myLead.transactionTime__c.hour())+':'+String.valueOf(myLead.transactionTime__c.minute())+':'+String.valueOf(myLead.transactionTime__c.second());
            System.debug('Hora');
            System.debug(myLead.transactionTime__c);
            //objToJSON.HoraTransaccion = hora[0];
            objToJSON.HoraTransaccion = hora;
        }else{
            System.debug('Sin hora');
            objToJSON.HoraTransaccion = '00:00:00';
        }
        objToJSON.rut = myLead.rut__c != null?myLead.rut__c:'';
        objToJSON.nombre = myLead.FirstName != null?myLead.FirstName:'';
        objToJSON.apellidoPaterno = myLead.lastName != null?myLead.lastName:'';
        objToJSON.apellidoMaterno = myLead.motherLastName__c != null?myLead.motherLastName__c:'';
        objToJSON.rentaLiquida = myLead.income__c != null?String.valueOf(myLead.income__c):'0';
        objToJSON.email = myLead.Email != null?myLead.Email:'';
        if(myLead.MobilePhone != null){
            objToJSON.telefono = myLead.MobilePhone;
        }else if(myLead.Phone != null){
            objToJSON.telefono = myLead.Phone;
        }else if(myLead.workPhone__c != null){
            objToJSON.telefono = myLead.workPhone__c;
        }
        objToJSON.valorVehiculo = myLead.carPrice__c != null?String.valueOf(myLead.carPrice__c):'0';
        objToJSON.montoPie = myLead.downPayment__c != null?String.valueOf(myLead.downPayment__c):'0';
        objToJSON.tipoVehiculo = myLead.vehicleType__c != null?myLead.vehicleType__c:'';
        objToJSON.situacionLaboral = myLead.workType__c != null?myLead.workType__c:'';
        objToJSON.marcaVehiculo = myLead.carBrandId__c != null?String.valueOf(myLead.carBrandId__c):'0';
        objToJSON.marcaVehiculoNombre = myLead.carBrandDescription__c != null?myLead.carBrandDescription__c:'';
        objToJSON.modelo = myLead.carModelId__c != null?String.valueOf(myLead.carModelId__c):'0';
        objToJSON.modeloNombre = myLead.carModelDescription__c != null?myLead.carModelDescription__c:'';
        objToJSON.version = myLead.carVersion__c != null?myLead.carVersion__c:'';
        objToJSON.valorCuota = myLead.monthlyPayment__c != null?String.valueOf(myLead.monthlyPayment__c):'0';
        objToJSON.idTripleta = myLead.tripletId__c != null?myLead.tripletId__c:'0';
        objToJSON.anioVehiculo = myLead.carYear__c != null?myLead.carYear__c:null;
        objToJSON.escenario_interes = myLead.loanSetting__c != null?myLead.loanSetting__c:'0';
        objToJSON.Canal = myLead.channelId__c != null?myLead.channelId__c:'';
        objToJSON.concesionario = myLead.salesChannel__c != null?myLead.salesChannel__c:'';
        objToJSON.local = myLead.Locales__c != null?myLead.Locales__c:'';
        objToJSON.nombreEmpresa = myLead.Company != null?myLead.Company:'';
        objToJSON.antiguedadLaboral = myLead.monthsWorked__c != null?String.valueOf(myLead.monthsWorked__c):'0';
        objToJSON.plazoCredito = myLead.termDescription__c != null?myLead.termDescription__c:'';
        objToJSON.codigoProducto = myLead.productCode__c != null?myLead.productCode__c:'';
        objToJSON.tipoCredito = myLead.loanType__c != null?myLead.loanType__c:'';
        objToJSON.porcentaje = myLead.downPaymentPercentage__c != null?String.valueOf(myLead.downPaymentPercentage__c):'0';
        objToJSON.meses = myLead.terms__c != null?myLead.terms__c:'';
        objToJSON.fuente = '';
        objToJSON.estado = myLead.status;
        objToJSON.sub_estado = myLead.status__c;
        objToJSON.id = myLead.Id;
        return JSON.serialize(objToJSON);
    }
}